const { chromium } = require("playwright-core");
const path=require("path"); const fs=require("fs");
const CHROME=["/home/jeroen/.cache/ms-playwright/chromium-1200/chrome-linux64/chrome","/usr/bin/google-chrome-stable"].find(p=>fs.existsSync(p));
const bundle=fs.readFileSync(path.resolve("node_modules/nostr-tools/lib/nostr.bundle.js"),"utf8");
(async()=>{
  const browser=await chromium.launch({executablePath:CHROME,headless:true,args:["--no-sandbox","--disable-dev-shm-usage"]});
  const page=await browser.newPage({viewport:{width:1200,height:800}});
  await page.route("**/unpkg.com/**",r=>r.fulfill({status:200,contentType:"application/javascript",body:bundle}));
  await page.routeWebSocket("**",()=>{});
  await page.goto("file://"+path.resolve("index.html"),{waitUntil:"domcontentloaded"});
  await page.waitForSelector(".card:not(.skeleton)",{timeout:12000});
  const collapsed=()=>page.locator(".toolbar.collapsed").count();
  console.log("at top, collapsed:", await collapsed());
  await page.evaluate(()=>window.scrollTo(0,600)); await page.waitForTimeout(250);
  console.log("after scroll 600, collapsed:", await collapsed());
  await page.locator("#tagToggle").click(); await page.waitForTimeout(250);
  console.log("after toggle click, collapsed:", await collapsed(), "(want 0)");
  console.log("toolbar classes:", await page.locator(".toolbar").getAttribute("class"));
  await browser.close();
})().catch(e=>{console.error(e.message);process.exit(1)});
